dep-word2vec:
	pip install gensim
	pip install scikit-learn
	pip install matplotlib

run-word2vec:
	python 1.word2vec.py

dep-bert:
	pip install torchvision
	pip install pytorch-transformers
	pip install scikit-learn
	pip install matplotlib

run-bert:
	python 3.bert.py

