dep-simplernn:
	pip install tensorflow
	pip install keras_preprocessing

run-simplernn:
	python 1.simplernn.py

dep-lstm:
	pip install tensorflow
	pip install keras_preprocessing

run-lstm:
	python 2.lstm.py

dep-bilstm:
	pip install tensorflow
	pip install keras_preprocessing

run-bilstm:
	python 3.bilstm.py

dep-gru:

run-gru:
	python 4.gru.py